apiVersion: apps/v1
kind: Deployment
metadata:
  name: saya0
  labels:
    app: myapp
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: week4
        image: sayali063/newimage0:new_version
        ports:
        - containerPort: 3000